version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_USER=admin
      - DB_PASSWORD=password123
      - DB_HOST=db
      - DB_NAME=appdb
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - ./frontend:/usr/src/frontend # Monta el frontend para que el backend lo sirva